### ISSUE TITLE
Original CT dataset

### ISSUE THREAD

**Issue by gzliyu** [abrilcf/mednerf#13]
Dear author,
Would you share the original CT dataset?
Yu

**Comment by abrilcf** [comment]
Hi, you can access the data [here](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=80969771)

**Comment by gzliyu** [comment]
Hi,
Noted with thanks
________________________________

**Comment by povolann** [comment]
> Hi, you can access the data [here](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=80969771)

Hi @abrilcf , by any chance do you still know which Subject IDs you used from the original CT data? And also, I think this link is only for the chest data. Is it possible to download also the original CT data for the knee? Thanks!
