### ISSUE TITLE
The Issue of Inability to Reproduce Identical Results

### ISSUE THREAD

**Issue by yangtcai** [abrilcf/mednerf#15]
Hi, Authors, first and foremost, I would like to express my admiration for your extraordinary work. It truly is remarkable.
I have been attempting to reproduce your results and have encountered a few challenges along the way. I used the command ```python3 train.py configs/knee.yaml```, with a minor modification to the batch size (increasing it to 8). After training for 144,000 iterations, I observed some discrepancies in my results.

<img width="1241" alt="image" src="https://github.com/abrilcf/mednerf/assets/77475012/ff053787-a167-4658-b546-ceec1a935a81">
<img width="1214" alt="image" src="https://github.com/abrilcf/mednerf/assets/77475012/d43a00c7-aa48-44e0-99e6-60018077b0e9">
The images produced from my run appear to be different from those you presented in Fig3 of your documentation. It's quite possible that I might be overlooking something, so I was wondering if you could possibly shed some light on this matter.

Any guidance or suggestions you can provide would be greatly appreciated. Thank you in advance for your assistance and for the phenomenal work you have shared with the community.

**Comment by abrilcf** [comment]
Hi there,

thank you for your interest in our work. It seems that the results you're getting look too bright. Are these outputs of the training or inference using the "optimize G only" file ?

This issue might be of your interest (#14 )

**Comment by yangtcai** [comment]
Thank you for your response. I apologize for any lack of clarity in my previous communications. The results I mentioned pertain to the output of the training process. Based on your observations, it appears that my results are overly bright. Could you kindly provide some guidance on how I might address this issue?
