### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by gpqls** [abrilcf/mednerf#2]
Hi, I just have a question about DDRs.

In paper, you said "Projection parameters  are chosen to evenly sample points on the surface of a sphere, specifically a slight horizontal elevation of 70-85 degrees and ,  for a full 360- degree vertical rotation. ".

It meas, https://drive.google.com/file/d/1msiXso-nVDqdKWwoD6v129lYjOx7IXy5/view?usp=sharing like this picture?

You generate DDR with that degree at every 5 vertical degree?

**Comment by gpqls** [comment]
And I can't run "python train.py configs/chest.yaml".
It occurs error below.

> Traceback (most recent call last):
  File "train.py", line 140, in <module>
    x_real = get_nsamples(train_loader, ntest)
  File "/content/drive/MyDrive/mednerf/mednerf/graf-main/graf/utils.py", line 67, in get_nsamples
    x_next = next(data_loader)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 720, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 247, in __iter__
    for idx in self.sampler:
  File "/content/drive/MyDrive/mednerf/mednerf/graf-main/graf/utils.py", line 45, in InfiniteSampler
    yield order[i]
IndexError: index -1 is out of bounds for axis 0 with size 0

I don't know how to train this model with dataset.

**Comment by abrilcf** [comment]
Hi, 
The projection parameters described in that sentence refer to the camera matrices used by the model, not for generating the DRRs. For the DRRs, the elevation angle is fixed to 90 degrees. This was to consider slight variations in the detector of the different scans, and so the model is not too sensitive to those changes.

**Comment by gpqls** [comment]
What is camera matrix's mean? Didn't this mean the location of the camera?

**Comment by gpqls** [comment]
Hi,
I still wonder about 70-85 projection parameter. DRR data is fixed to 90 degrees, but how to use 70-85 degree when use model?
I can't understand about that.

And, in chest xray images, you use 20*72=1,440 images. About "20", that means 20 people chest x-ray?

**Comment by abrilcf** [comment]
Hi,
Sorry for the late reply.
1) A camera matrix describes the mapping from 3D to 2D. It does includes the camera location (camera extrinsics), but also the 3D-2D transformation (camera intrinsics). Here's [a great explanation of these concepts](https://ksimek.github.io/2012/08/14/decompose/)
2) The 70-85 choice doesn't really affect results. You can fix it to 90. You can observe the effect by running the [script](https://github.com/abrilcf/mednerf/blob/main/graf-main/eval.py#L207)
3) Exactly, 20 CT scans each from 20 patients.

**Comment by gpqls** [comment]
Thank you! I got it.

And, 
1. Did you apply nerf to each of 20 people or did you apply to each of 20 people as one common nerf? Where can I find the code for this content?

2. Is it correct that you set train and valid as the same dataset in the code?  If not, where can I find the code to check how the dataset was divided?

**Comment by abrilcf** [comment]
1. We train a single model for each category (chest and knee). So, one model for all of the instances.
2. Since the datasets were too small, we arbitrarily took out for testing: Knee - 1 instance, and for chest 4 instances. We arbitrarily picked the first instances. For the renderings of X-ray projections, we try with instances from [this dataset](https://data.mendeley.com/datasets/t9ndx37v5h/1) as well for knee. If you substitute with an instance from the training dataset, then it would be like "searching" the closest learned instance given a single projection

**Comment by zcc861007** [comment]
Hi Abril, 

According to your answer above, do you mean that you trained the GAN, simultaneously using X-ray sequences of 20 persons (e.g., for the chest)? If I have a X-ray sequence of only ONE person, can I train the GAN? 

Also, in the code shown below, should N be equal to 72 instead of 40?
https://github.com/abrilcf/mednerf/blob/0d3e07519afe2e6b8f51b1f19f2043d627c2b319/graf-main/graf/config.py#L94

Thanks!

**Comment by gpqls** [comment]
Aren't the four random datasets you brought already used for model training? 
https://github.com/abrilcf/mednerf/blob/0d3e07519afe2e6b8f51b1f19f2043d627c2b319/graf-main/train.py#L89-L91
I don't know where "those four instances" came from.

**Comment by abrilcf** [comment]
Hi C. Zhou,

Yes, you can train a model using a single instance. However, it may overfit to a point in which is hardly capable to render novel views for an unseen X-ray at inference time.
It looks like we missed that N value. One could think that would hurt results when testing the model but it may indicate it doesn't. As we do use N=72 at inference time.

**Comment by abrilcf** [comment]
Hi gpqls,
I meant that we left the first 4 instances of the chest dataset for validation.

**Comment by gpqls** [comment]
Hi, abrilcf. Thank you for answer.
Can you tell me the location of the code that left 4 instances?

**Comment by zcc861007** [comment]
Hi Abril. Thanks for your answers! I feel I got the point. Do you mean that there are 20 chest NeRFs for the 20 subjects during training? In such way, the GAN can be trained by more Xray-DRR pairs?

**Comment by abrilcf** [comment]
Hi gpqls,
That's manually done in the `render_xray_G.py` and `render_xray_G_Z.py` scripts. Now I understand the confusion with the `val_dataset = train_dataset ` line, you see FID and KID metrics are used for evaluation. Both compare the distribution of real images (those used for training) and the learned distribution.

**Comment by abrilcf** [comment]
Hi zcc861007,
Yes, That would certainly help generalization

**Comment by gpqls** [comment]
Thanks to this, I found out that real images and learned distribution are compared and scored in FID and KID.
