### ISSUE TITLE
About the baseline experiment pixel-nerf

### ISSUE THREAD

**Issue by djx99** [abrilcf/mednerf#4]
I'm curious how you did your pixelnerf comparison experiment. Are you directly replacing the natural or rendered images in the nerf with the X-ray images? Or is there another way?

**Comment by abrilcf** [comment]
Hi,
We trained pixelNerf from scratch with our data. For that, we modified the dataloader, especially the camera part. You need the camera matrices to train pixelNerf. Since we generated the DRRs using [Plastimatch](http://plastimatch.org/index.html), we referred to their [projection geometry](http://plastimatch.org/proj_geometry_15.html) and [Projection matrix](http://plastimatch.org/proj_mat_file_format.html) documentation to generated the camera matrices.

**Comment by djx99** [comment]
thank you for your reply. Do you keep specific X-ray data, camera parameters and loading codes? I haven't done this before, I'd appreciate it if you could share

**Comment by djx99** [comment]
thank you for your reply. Do you keep specific X-ray data, camera parameters and loading codes? I haven't done this before, I'd appreciate it if you could share

**Comment by abrilcf** [comment]
Sure, I thought the link to the data contained the .txt files with the camera poses, but not. I just added that and updated the repo. Please refer to [this link](https://drive.google.com/file/d/1xasjb7Q2nROiwDDeUVHrC6GjIEAm0HRs/view) for the poses and take a look at the dataloader [script](https://github.com/jonathanfrawley/pixel-nerf/blob/master/src/data/drrDataset.py)

**Comment by djx99** [comment]
thank you~ I see and I'll try it. I've been using nerf directly for CT reconstruction recently, but the results are not ideal. 
![000](https://user-images.githubusercontent.com/86991107/190936428-d76b8384-2091-4013-aedc-5884ff762819.png)
![project_5](https://user-images.githubusercontent.com/86991107/190936436-c4eb2781-7ce1-4662-92c3-3532023ba38c.png)
The first is the reconstruction result of 200k iterations, and the second is the GT.
Your article thinks that using nerf or pixelnerf directly is not effective. Can you use nerf as a comparison algorithm? Can you get a general result? Does nerf not get clean reconstruction results at all?

**Comment by abrilcf** [comment]
the objective of our work was to apply neural radiance fields in medical images, but there are differences compared to "natural images"; color, structures, camera system, availability, etc. So our contribution is an attempt to bridge that gap by using the "most suitable" approach (in that time) to our task. One of my collaborators got very good results with pixelNeRF but using the whole CT volume, you can take a look at [the script](https://github.com/jonathanfrawley/pixel-nerf/blob/d0cac550c3652176e1b28c90c0aa4bdbff718a2f/eval/render_ct.py). In a way, I think you can call that a "general result"..? However, we couldn't manage to make it work with few projections.

**Comment by djx99** [comment]
I'm very sorry for interrupting so many times. Do you have the email address of this collaborator, I would like to inquire about the ct results of pixelnerf. Because he only uploaded the configuration file, and did not add comments or run commands, etc., so I would not use this configuration file. Or can you tell me, how can I run pixelnerf on ct data? Thank you very much.

**Comment by djx99** [comment]
And how do you get the value of focal near and far? how to compute？Do these values have an effect on the results？

**Comment by povolann** [comment]
> Hi, We trained pixelNerf from scratch with our data. For that, we modified the dataloader, especially the camera part. You need the camera matrices to train pixelNerf. Since we generated the DRRs using [Plastimatch](http://plastimatch.org/index.html), we referred to their [projection geometry](http://plastimatch.org/proj_geometry_15.html) and [Projection matrix](http://plastimatch.org/proj_mat_file_format.html) documentation to generated the camera matrices.

From this, it seems that the parameters `cx` and `cy` are 0 for the knee and chest images. Is it really like that or I am missing something?

**Comment by abrilcf** [comment]
That is correct, both are zero. Basically, the intrinsic parameters are fixed for all chest instances or knees.
