### ISSUE TITLE
applications

### ISSUE THREAD

**Issue by free-soellingeraj** [abrilcf/mednerf#7]
If I understand correctly, the motivation of this study is to require fewer sensor rotations thus reducing the patient exposure to harmful radiation.  Using a single rotation of the sensor, you're able to reproduce a pretty good 3d reconstruction. I am curious if another application might be to improve the accuracy of 3D reconstruction given all rotations of the sensor.  I have an application where it would be beneficial to improve the accuracy of the 3d reconstruction.  I am trying to understand the difference between using something like mednerf vs using a SIFT type algorithm to do registration, and how that might improve my 3d reconstruction over what I get with current siemens SOTA on CTA images.

**Comment by abrilcf** [comment]
Hi, I haven't worked with SIFT algorithms, so I'm not able to accurately describe the technical differences compared from nerf based methods. But from my understanding with SIFT you can compute both the camera and motion parameters. Some kind prior camera info is often necessary for nerf methods. So I think you could use them in a complementary fashion were you predict camera matrices using SIFT, use them to train a nerf and incorporate the motion parameters somewhere in the process. I'd imagine this extra info could lead to more accurate results in principle as you'd reduce the space of possible mappings between the image domains. I'm not sure if this has been done before or if that makes any sense to your application.
